import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const RoomCard = ({ room, onJoin, isJoining = false }) => {
    const host = typeof room.host === 'object' ? room.host : null;
    const guest = typeof room.guest === 'object' ? room.guest : null;
    const currentPlayersCount = (host ? 1 : 0) + (guest ? 1 : 0);
    const maxPlayersCount = room.maxPlayers || 2;
    return (_jsxs("div", { className: "p-5 bg-slate-900/60 border border-white/10 backdrop-blur-xl rounded-2xl shadow-xl flex justify-between items-center hover:border-pool-cyan/40 transition duration-300", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "px-2 py-0.5 text-[10px] font-extrabold uppercase bg-pool-cyan/15 text-pool-cyan border border-pool-cyan/20 rounded-md tracking-wider", children: "Public" }), _jsxs("h4", { className: "text-sm font-bold font-display text-slate-400", children: ["Room Code: ", _jsx("span", { className: "text-white text-base select-all", children: room.roomId })] })] }), _jsxs("p", { className: "text-xs font-body text-slate-400 mt-2", children: ["Host: ", _jsx("span", { className: "text-slate-200 font-semibold", children: host?.username || 'Unknown' })] }), _jsxs("p", { className: "text-[10px] font-body text-slate-500 mt-1", children: ["Rank Limit: ", _jsx("span", { className: "text-pool-cyan font-bold", children: host?.rank || 'Beginner' })] })] }), _jsxs("div", { className: "flex flex-col items-end gap-3", children: [_jsxs("div", { className: "text-xs font-semibold text-slate-400 font-display flex items-center gap-1.5", children: [_jsx("span", { className: `inline-block w-2.5 h-2.5 rounded-full ${currentPlayersCount < maxPlayersCount ? 'bg-emerald-500 animate-pulse' : 'bg-rose-500'}` }), currentPlayersCount, " / ", maxPlayersCount, " Players"] }), _jsx("button", { onClick: () => onJoin(room.roomId), disabled: isJoining || currentPlayersCount >= maxPlayersCount, className: `py-2 px-4 font-display text-xs font-bold rounded-xl shadow-md transition-all duration-300 ${currentPlayersCount >= maxPlayersCount
                            ? 'bg-white/5 border border-white/5 text-slate-600 cursor-not-allowed'
                            : 'bg-gradient-to-r from-pool-cyan to-pool-cyan/85 hover:shadow-lg hover:shadow-pool-cyan/15 hover:brightness-110 active:scale-95 text-pool-dark'}`, children: isJoining ? 'Joining...' : 'Join Room' })] })] }));
};
export default RoomCard;
