import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const PlayerCard = ({ user, isHost = false, label }) => {
    if (!user) {
        return (_jsxs("div", { className: "flex flex-col items-center justify-center p-8 bg-slate-900/30 border border-white/5 border-dashed rounded-2xl min-h-[220px] transition-all duration-300 relative overflow-hidden group", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-tr from-pool-purple/5 to-transparent opacity-50 group-hover:opacity-85 transition-opacity" }), _jsx("div", { className: "w-16 h-16 rounded-full border-2 border-white/10 flex items-center justify-center text-2xl text-slate-500 mb-4 animate-pulse relative z-10", children: "?" }), _jsx("div", { className: "text-slate-400 font-display font-semibold tracking-wider text-sm mb-1 relative z-10", children: "Waiting for Opponent..." }), _jsx("div", { className: "text-slate-500 font-body text-xs relative z-10", children: "Share your room code to start playing." })] }));
    }
    const level = Math.floor(user.xp / 1000) + 1;
    const gamesPlayed = user.wins + user.losses;
    const winRate = gamesPlayed > 0 ? Math.round((user.wins / gamesPlayed) * 100) : 0;
    return (_jsxs("div", { className: "p-6 bg-slate-900/80 border border-white/10 backdrop-blur-xl rounded-2xl shadow-xl flex flex-col items-center min-h-[220px] hover:border-pool-cyan/35 transition-all duration-300 relative", children: [_jsxs("div", { className: "absolute top-3 right-3 flex gap-1", children: [isHost && (_jsx("span", { className: "px-2 py-0.5 text-[9px] font-extrabold uppercase bg-amber-500/25 border border-amber-500/40 text-amber-300 rounded-md", children: "Host" })), label && (_jsx("span", { className: "px-2 py-0.5 text-[9px] font-extrabold uppercase bg-pool-cyan/15 border border-pool-cyan/30 text-pool-cyan rounded-md", children: label }))] }), _jsxs("div", { className: "w-16 h-16 rounded-full bg-gradient-to-tr from-pool-cyan/30 to-pool-purple/20 border border-pool-cyan/40 flex items-center justify-center text-3xl shadow-lg relative mb-4", children: [_jsx("span", { className: "select-none", children: user.avatar === 'avatar_1' ? '👤' : user.avatar || '👤' }), _jsxs("div", { className: "absolute -bottom-1 -right-1 w-6 h-6 rounded-full bg-pool-cyan border border-slate-950 flex items-center justify-center text-[10px] font-bold text-slate-950 font-display", children: ["L", level] })] }), _jsx("h3", { className: "text-lg font-bold font-display text-white truncate max-w-full text-center", children: user.username }), _jsx("p", { className: "text-xs font-semibold uppercase tracking-wider text-pool-cyan/80 mt-0.5 font-display", children: user.rank }), _jsxs("div", { className: "grid grid-cols-3 gap-2 w-full mt-5 border-t border-white/5 pt-4 text-center", children: [_jsxs("div", { children: [_jsx("div", { className: "text-[10px] font-semibold text-slate-500 uppercase tracking-wide", children: "Coins" }), _jsxs("div", { className: "text-xs font-extrabold text-amber-400 font-display mt-0.5", children: ["\uD83E\uDE99 ", user.coins] })] }), _jsxs("div", { children: [_jsx("div", { className: "text-[10px] font-semibold text-slate-500 uppercase tracking-wide", children: "Record" }), _jsxs("div", { className: "text-xs font-extrabold text-white font-display mt-0.5", children: [user.wins, "W - ", user.losses, "L"] })] }), _jsxs("div", { children: [_jsx("div", { className: "text-[10px] font-semibold text-slate-500 uppercase tracking-wide", children: "Win Rate" }), _jsxs("div", { className: "text-xs font-extrabold text-emerald-400 font-display mt-0.5", children: [winRate, "%"] })] })] })] }));
};
export default PlayerCard;
